{
 "title": "6.8-skillbox",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "query": "consul" }
  ]
 },
 "panels": [
  {
   "title": "Доступно места на жёстком диске в GB",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\", device!=\"tmpfs\", job=\"$job\"} / 1024 / 1024 / 1024",
     "legendFormat": "Free {{volume}}-"
    }
   ]
  },
  {
   "title": "Загрузка проца в процентах за 1 мин.",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "floor(100 - (avg by (instance) (rate (node_cpu_seconds_total{mode=\"idle\", job=\"$job\"}[1m])) * 100))",
     "legendFormat": "{{label_name}}-"
    }
   ]
  },
  {
   "title": "CPU core number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Total space HDD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes) / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "floor(node_memory_MemTotal_bytes / 1024 / 1024 / 1024)"
    }
   ]
  },
  {
   "title": "Utilization rate of each partition",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100-(node_filesystem_avail_bytes / node_filesystem_size_bytes)*100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100-((node_memory_MemFree_bytes + node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100-(avg(irate(node_cpu_seconds_total{mode=\"idle\"}[30s])))*100"
    }
   ]
  },
  {
   "title": "Node_Load-5",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "targets": [
    { "expr": "node_load5" }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (device) (irate(node_disk_read_bytes_total{device!=\"sr0\", job=\"$job\"}[5m]))",
     "legendFormat": "read -{{volume}}"
    },
    {
     "expr": "avg by (device) (irate(node_disk_written_bytes_total{device!=\"sr0\", job=\"$job\"}[5m]))",
     "legendFormat": "write -{{volume}}"
    }
   ]
  },
  {
   "title": "Network Mb/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"enp0s3\", job=\"$job\"}[5m])*8",
     "legendFormat": "Received-Download"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"enp0s3\", job=\"$job\"}[5m])*8>0",
     "legendFormat": "Sent-Upload"
    }
   ]
  }
 ]
}